name: floodplanet-smk
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.11.11
  - snakemake=9.19.0
  - numpy=2.2.2
  - pandas
  - geopandas
  - rasterio
  - shapely
  - scikit-image=0.26.0
  - matplotlib
  - pyyaml
  - pip
  - pip:
      - planet==3.6.0
